# Generated by Django 2.1 on 2018-10-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondetail',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='abilitytest',
            name='result',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Bậc năng lực'),
        ),
        migrations.AlterField(
            model_name='questiondetail',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Nội dung'),
        ),
    ]
