# Generated by Django 2.1 on 2018-10-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0002_auto_20181018_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitytest',
            name='phase',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Đợt đánh giá'),
        ),
        migrations.AlterField(
            model_name='abilitytype',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='questiondetail',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Nội dung'),
        ),
    ]
