# Generated by Django 2.1 on 2018-10-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0003_auto_20181019_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilitytest',
            name='phase',
        ),
        migrations.AddField(
            model_name='abilitytest',
            name='version',
            field=models.SmallIntegerField(null=True, verbose_name='Đợt đánh giá'),
        ),
        migrations.AlterField(
            model_name='answerdetail',
            name='rank',
            field=models.SmallIntegerField(null=True, verbose_name='Thaaaaaaang điểm'),
        ),
    ]
