# Generated by Django 2.1 on 2018-10-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0004_auto_20181019_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerdetail',
            name='rank',
            field=models.SmallIntegerField(null=True, verbose_name='Điểm'),
        ),
    ]
