# Generated by Django 2.1 on 2018-10-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0005_auto_20181019_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilitytest',
            name='version',
        ),
    ]
