# Generated by Django 2.1 on 2018-10-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0007_questiondetail_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondetail',
            name='code',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Mã mục'),
        ),
    ]
