# Generated by Django 2.1 on 2018-10-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0008_auto_20181019_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='qadetail',
            name='num_order',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='STT'),
        ),
    ]
