# Generated by Django 2.1 on 2018-10-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0009_qadetail_num_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qadetail',
            options={'ordering': ['num_order'], 'verbose_name': 'Chi tiết đánh giá', 'verbose_name_plural': 'Chi tiết đánh giá'},
        ),
        migrations.AlterField(
            model_name='questiondetail',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mã mục'),
        ),
    ]
