# Generated by Django 2.1 on 2018-10-20 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competence', '0010_auto_20181020_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construct', models.CharField(blank=True, max_length=200, null=True, verbose_name='Form')),
            ],
        ),
        migrations.AddField(
            model_name='abilitytest',
            name='form_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='competence.FormVersion', verbose_name='Form'),
        ),
    ]
