# Generated by Django 2.1 on 2018-10-07 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_auto_20180926_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbtc',
            options={'ordering': ['id'], 'permissions': (('manage_TBTC', 'Quản lý TBTC'),), 'verbose_name': 'Thiết bị Thi công', 'verbose_name_plural': 'Thiết bị Thi công'},
        ),
        migrations.AlterModelOptions(
            name='tbtcstatuslog',
            options={'ordering': ['-id'], 'verbose_name': 'Tình trạng TBTC', 'verbose_name_plural': 'Tình trạng TBTC'},
        ),
        migrations.AlterField(
            model_name='tbtcdocument',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Project', verbose_name='Công trình'),
        ),
    ]
