# Generated by Django 2.1 on 2018-10-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_auto_20181012_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datelog',
            name='over9',
        ),
    ]
