# Generated by Django 2.1 on 2018-10-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_remove_datelog_over9'),
    ]

    operations = [
        migrations.AddField(
            model_name='datelog',
            name='over9',
            field=models.BooleanField(default=False, verbose_name='Trực đêm'),
        ),
    ]
