# Generated by Django 2.1 on 2018-10-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0007_datelog_over9'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datelog',
            old_name='shift_1',
            new_name='shift1',
        ),
        migrations.RenameField(
            model_name='datelog',
            old_name='shift_2',
            new_name='shift2',
        ),
        migrations.RenameField(
            model_name='datelog',
            old_name='shift_3',
            new_name='shift3',
        ),
    ]
