# Generated by Django 2.0.5 on 2018-08-21 22:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_in', models.DateField(help_text='YYYY-MM-DD', null=True, verbose_name='Ngày nhận phân công')),
                ('d_out', models.DateField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Ngày hết hiệu lực phân công')),
            ],
            options={
                'verbose_name': 'Phân công',
                'verbose_name_plural': 'Phân công',
                'ordering': ['project', '-d_in', 'd_out'],
            },
        ),
        migrations.CreateModel(
            name='DateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='Date', null=True)),
                ('in1', models.TimeField(blank=True, null=True)),
                ('out1', models.TimeField(blank=True, null=True)),
                ('in2', models.TimeField(blank=True, null=True)),
                ('out2', models.TimeField(blank=True, null=True)),
                ('in3', models.TimeField(blank=True, null=True)),
                ('out3', models.TimeField(blank=True, null=True)),
                ('over9', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', 'project'],
            },
        ),
        migrations.CreateModel(
            name='Deparment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('short_text', models.CharField(help_text='2 ký tự', max_length=2, null=True, unique=True, verbose_name='Mã')),
            ],
            options={
                'verbose_name': 'Bộ phận',
                'verbose_name_plural': 'Bộ phận',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OfficeTimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dati', models.DateTimeField(blank=True, help_text='Date, Time', null=True)),
                ('status', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
            ],
            options={
                'ordering': ['-dati'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_text', models.CharField(max_length=100, verbose_name='Tên')),
                ('short_text', models.CharField(help_text='2 ký tự', max_length=2, null=True, unique=True, verbose_name='Mã')),
            ],
            options={
                'verbose_name': 'Chức vụ',
                'verbose_name_plural': 'Chức vụ',
                'ordering': ['position_text'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dự án')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phạm vi công việc')),
                ('location', models.CharField(max_length=200, null=True, verbose_name='Địa điểm')),
                ('no_paid', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số lần thanh toán')),
                ('status', models.CharField(choices=[('DT', 'Đang Dự thầu'), ('CB', 'Đang Chuẩn bị'), ('TC', 'Đang Thi công'), ('HT', 'Đã Hoàn thành Thi công'), ('TL', 'Đã Thanh lý Hợp đồng')], default='DT', max_length=2, verbose_name='Trạng thái')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú')),
                ('allowed_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dự án',
                'verbose_name_plural': 'Dự án',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dati', models.DateTimeField(blank=True, help_text='Date, Time', null=True)),
                ('status', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.Project')),
            ],
            options={
                'ordering': ['-dati'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ và Tên')),
                ('office', models.BooleanField(default=False, verbose_name='Làm ở Văn phòng')),
                ('MaNV', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mã Nhân viên')),
                ('dob', models.DateField(default='1900-12-31', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày sinh')),
                ('d_in', models.DateField(default='1900-12-31', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày vào làm')),
                ('d_out', models.DateField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Ngày nghỉ việc')),
                ('pros', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chuyên môn')),
                ('cmnd', models.CharField(default='888888888', help_text='CMND 9 số hoặc CCCD 12 số', max_length=12, null=True, validators=[django.core.validators.RegexValidator(regex='(^\\d{9}$|^\\d{12}$)')], verbose_name='Số CMND/CCCD')),
                ('certi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Chứng chỉ')),
                ('pob', models.CharField(default='Sài Gòn', max_length=200, null=True, verbose_name='Nơi sinh')),
                ('hk', models.CharField(default='Sài Gòn', max_length=200, null=True, verbose_name='Hộ Khẩu')),
                ('address', models.CharField(default='Sài Gòn', max_length=200, null=True, verbose_name='Địa chỉ liên lạc')),
                ('tel', models.CharField(default='01234567890', help_text='Di động 10 số hoặc 11 số', max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='(^0\\d{9}$|^0\\d{10}$)')], verbose_name='SĐT')),
                ('deparment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.Deparment', verbose_name='Bộ Phận')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.Position', verbose_name='Chức vụ')),
            ],
            options={
                'verbose_name': 'Nhân sự',
                'verbose_name_plural': 'Nhân sự',
                'ordering': ['id'],
                'permissions': (('office_check', 'Chấm công Văn phòng'),),
            },
        ),
        migrations.CreateModel(
            name='TBTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên Thiết bị')),
                ('number', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.Project')),
            ],
            options={
                'verbose_name': 'Thiết bị thi công',
                'verbose_name_plural': 'Thiết bị thi công',
            },
        ),
        migrations.CreateModel(
            name='TBVT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên Thiết bị')),
                ('number', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.Project')),
            ],
            options={
                'verbose_name': 'Thiết bị - Vật tư',
                'verbose_name_plural': 'Thiết bị - Vật tư',
            },
        ),
        migrations.AddField(
            model_name='projecttimelog',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.Staff'),
        ),
        migrations.AddField(
            model_name='project',
            name='chief',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('deparment', 6), ('deparment', 3), _connector='OR'), ('d_out__isnull', True)), null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.Staff', verbose_name='Chỉ huy Trưởng'),
        ),
        migrations.AddField(
            model_name='officetimelog',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.Staff'),
        ),
        migrations.AddField(
            model_name='datelog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.Project'),
        ),
        migrations.AddField(
            model_name='datelog',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.Staff'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.Project', verbose_name='Dự án'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='staff',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('deparment', 6), ('deparment', 3), _connector='OR'), ('d_out__isnull', True)), null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.Staff', verbose_name='Nhân sự'),
        ),
    ]
