# Generated by Django 2.0.5 on 2018-08-21 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaVB', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mã VB')),
                ('name', models.CharField(max_length=200, verbose_name='Tên')),
                ('date_created', models.DateField(default='1900-12-31', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày lập')),
            ],
            options={
                'verbose_name': 'Văn bản',
                'verbose_name_plural': 'Văn bản',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TBTCBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nhãn hiệu TBTC')),
                ('short_text', models.CharField(help_text='1 ký tự', max_length=1, null=True, unique=True, verbose_name='Mã')),
            ],
            options={
                'verbose_name': 'Nhãn hiệu TBTC',
                'verbose_name_plural': 'Nhãn hiệu TBTC',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TBTCType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên TBTC')),
                ('short_text', models.CharField(help_text='3 ký tự', max_length=3, null=True, unique=True, verbose_name='Mã')),
            ],
            options={
                'verbose_name': 'Loại TBTC',
                'verbose_name_plural': 'Loại TBTC',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='tbtc',
            options={'ordering': ['id'], 'verbose_name': 'Thiết bị Thi công', 'verbose_name_plural': 'Thiết bị Thi công'},
        ),
        migrations.RemoveField(
            model_name='tbtc',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tbtc',
            name='number',
        ),
        migrations.AddField(
            model_name='tbtc',
            name='MaTBTC',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mã TB'),
        ),
        migrations.AddField(
            model_name='tbtc',
            name='d_in',
            field=models.DateField(default='1900-12-31', help_text='YYYY-MM-DD', null=True, verbose_name='Thời gian sử dụng'),
        ),
        migrations.AddField(
            model_name='tbtc',
            name='d_out',
            field=models.DateField(default='1900-12-31', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày ngưng sử dụng'),
        ),
        migrations.AddField(
            model_name='tbtc',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Staff', verbose_name='Người quản lý'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Project', verbose_name='Dự án'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='staff',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('deparment', 6), ('deparment', 3), _connector='OR'), ('d_out__isnull', True)), null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Staff', verbose_name='Nhân sự'),
        ),
        migrations.AlterField(
            model_name='datelog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Project'),
        ),
        migrations.AlterField(
            model_name='datelog',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Staff'),
        ),
        migrations.AlterField(
            model_name='officetimelog',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Staff'),
        ),
        migrations.AlterField(
            model_name='project',
            name='chief',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('deparment', 6), ('deparment', 3), _connector='OR'), ('d_out__isnull', True)), null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Staff', verbose_name='Chỉ huy Trưởng'),
        ),
        migrations.AlterField(
            model_name='projecttimelog',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Project'),
        ),
        migrations.AlterField(
            model_name='projecttimelog',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='deparment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Deparment', verbose_name='Bộ Phận'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Position', verbose_name='Chức vụ'),
        ),
        migrations.AlterField(
            model_name='tbtc',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Project', verbose_name='Công trình'),
        ),
        migrations.AlterField(
            model_name='tbvt',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Project'),
        ),
        migrations.AddField(
            model_name='tbtc',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.TBTCBrand', verbose_name='Nhãn hiệu'),
        ),
        migrations.AddField(
            model_name='tbtc',
            name='d_receive',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d_receive', to='summary.Document', verbose_name='Văn bản giao'),
        ),
        migrations.AddField(
            model_name='tbtc',
            name='d_return',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d_return', to='summary.Document', verbose_name='Văn bản trả'),
        ),
        migrations.AddField(
            model_name='tbtc',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.TBTCType', verbose_name='Tên'),
        ),
    ]
