# Generated by Django 2.0.5 on 2018-08-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_auto_20180821_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbtc',
            name='d_out',
            field=models.DateField(blank=True, default='1900-12-31', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày ngưng sử dụng'),
        ),
    ]
