# Generated by Django 2.0.5 on 2018-08-21 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_auto_20180821_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBTCManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Phân bổ TBTC',
                'verbose_name_plural': 'Phân bố TBTC',
                'ordering': ['project'],
            },
        ),
        migrations.RemoveField(
            model_name='tbtc',
            name='d_receive',
        ),
        migrations.RemoveField(
            model_name='tbtc',
            name='d_return',
        ),
        migrations.RemoveField(
            model_name='tbtc',
            name='project',
        ),
        migrations.RemoveField(
            model_name='tbtc',
            name='sponsor',
        ),
        migrations.AlterField(
            model_name='document',
            name='date_created',
            field=models.DateField(default='2018-08-21', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày lập'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='d_in',
            field=models.DateField(default='2018-08-21', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày vào làm'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.DateField(default='2018-08-21', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='tbtc',
            name='d_in',
            field=models.DateField(default='2018-08-21', help_text='YYYY-MM-DD', null=True, verbose_name='Thời gian sử dụng'),
        ),
        migrations.AlterField(
            model_name='tbtc',
            name='d_out',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Ngưng sử dụng'),
        ),
        migrations.AddField(
            model_name='tbtcmanage',
            name='d_receive',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d_receive', to='summary.Document', verbose_name='Văn bản giao'),
        ),
        migrations.AddField(
            model_name='tbtcmanage',
            name='d_return',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d_return', to='summary.Document', verbose_name='Văn bản trả'),
        ),
        migrations.AddField(
            model_name='tbtcmanage',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Project', verbose_name='Công trình'),
        ),
        migrations.AddField(
            model_name='tbtcmanage',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Staff', verbose_name='Người quản lý'),
        ),
        migrations.AddField(
            model_name='tbtcmanage',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.TBTC', verbose_name='Thiết bị'),
        ),
    ]
