# Generated by Django 2.0.5 on 2018-08-22 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_auto_20180821_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocation',
            options={'ordering': ['project', '-d_in', 'd_out'], 'verbose_name': 'Phân công Nhân sự', 'verbose_name_plural': 'Phân công Nhân sự'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['status'], 'verbose_name': 'Công trình', 'verbose_name_plural': 'Công trình'},
        ),
        migrations.AlterField(
            model_name='allocation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Project', verbose_name='Công trình'),
        ),
        migrations.AlterField(
            model_name='document',
            name='MaVB',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Mã VB'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_created',
            field=models.DateField(default='2018-08-22', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày lập'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Công trình'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='d_in',
            field=models.DateField(default='2018-08-22', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày vào làm'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.DateField(default='2018-08-22', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Họ và Tên'),
        ),
        migrations.AlterField(
            model_name='tbtc',
            name='d_in',
            field=models.DateField(default='2018-08-22', help_text='YYYY-MM-DD', null=True, verbose_name='Thời gian sử dụng'),
        ),
        migrations.AlterField(
            model_name='tbtcbrand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nhãn hiệu TBTC'),
        ),
        migrations.AlterField(
            model_name='tbtcmanage',
            name='d_receive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d_receive', to='summary.Document', verbose_name='Văn bản giao'),
        ),
        migrations.AlterField(
            model_name='tbtcmanage',
            name='d_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d_return', to='summary.Document', verbose_name='Văn bản trả'),
        ),
        migrations.AlterField(
            model_name='tbtctype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên TB'),
        ),
    ]
