# Generated by Django 2.1 on 2018-08-23 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_auto_20180822_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-date_crt'], 'verbose_name': 'Văn bản', 'verbose_name_plural': 'Văn bản'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='date_created',
        ),
        migrations.AddField(
            model_name='document',
            name='date_crt',
            field=models.DateField(default='2018-08-23', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày lập'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='d_in',
            field=models.DateField(default='2018-08-23', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày vào làm'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.DateField(default='2018-08-23', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='tbtc',
            name='d_in',
            field=models.DateField(default='2018-08-23', help_text='YYYY-MM-DD', null=True, verbose_name='Thời gian sử dụng'),
        ),
        migrations.AlterField(
            model_name='tbtcmanage',
            name='d_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='d_return', to='summary.Document', verbose_name='Văn bản trả'),
        ),
        migrations.AlterField(
            model_name='tbtcmanage',
            name='sponsor',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('deparment', 6), ('deparment', 3), _connector='OR'), ('d_out__isnull', True)), null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Staff', verbose_name='Người quản lý'),
        ),
    ]
