# Generated by Django 2.1 on 2018-08-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0007_auto_20180823_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_crt',
            field=models.DateField(default='2018-08-27', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày lập'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='d_in',
            field=models.DateField(default='2018-08-27', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày vào làm'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.DateField(default='2018-08-27', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='tbtc',
            name='d_in',
            field=models.DateField(default='2018-08-27', help_text='YYYY-MM-DD', null=True, verbose_name='Thời gian sử dụng'),
        ),
    ]
