# Generated by Django 2.1 on 2018-08-31 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0008_auto_20180827_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTBVT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
            ],
            options={
                'verbose_name': 'Xuất Vật tư',
                'verbose_name_plural': 'xuất Vật tư',
                'ordering': ['document'],
            },
        ),
        migrations.CreateModel(
            name='ImportTBVT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
            ],
            options={
                'verbose_name': 'Nhập Vật tư',
                'verbose_name_plural': 'Nhập Vật tư',
                'ordering': ['document'],
            },
        ),
        migrations.CreateModel(
            name='TBVTBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nhãn hiệu TBTC')),
                ('short_text', models.CharField(help_text='1 ký tự', max_length=1, null=True, unique=True, verbose_name='Mã')),
            ],
            options={
                'verbose_name': 'Nhãn hiệu TBTC',
                'verbose_name_plural': 'Nhãn hiệu TBTC',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TBVTType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên TB')),
                ('short_text', models.CharField(help_text='3 ký tự', max_length=3, null=True, unique=True, verbose_name='Mã')),
            ],
            options={
                'verbose_name': 'Loại TBTC',
                'verbose_name_plural': 'Loại TBTC',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Đơn vị')),
                ('short_text', models.CharField(help_text='1 ký tự', max_length=1, null=True, unique=True, verbose_name='Mã')),
            ],
            options={
                'verbose_name': 'Đơn vị',
                'verbose_name_plural': 'Đơn vị',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='officetimelog',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='projecttimelog',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projecttimelog',
            name='staff',
        ),
        migrations.AlterModelOptions(
            name='tbvt',
            options={'ordering': ['MaTBVT'], 'verbose_name': 'Thiết bị - Vật tư', 'verbose_name_plural': 'Thiết bị - Vật tư'},
        ),
        migrations.RemoveField(
            model_name='tbvt',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tbvt',
            name='number',
        ),
        migrations.RemoveField(
            model_name='tbvt',
            name='project',
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Project', verbose_name='Công trình'),
        ),
        migrations.AddField(
            model_name='tbvt',
            name='MaTBVT',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mã TBVT'),
        ),
        migrations.AddField(
            model_name='tbvt',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_crt',
            field=models.DateField(default='2018-08-31', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày lập'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='d_in',
            field=models.DateField(default='2018-08-31', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày vào làm'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.DateField(default='2018-08-31', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='tbtc',
            name='d_in',
            field=models.DateField(default='2018-08-31', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày mua'),
        ),
        migrations.DeleteModel(
            name='OfficeTimeLog',
        ),
        migrations.DeleteModel(
            name='ProjectTimeLog',
        ),
        migrations.AddField(
            model_name='importtbvt',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_vt', to='summary.Document', verbose_name='Văn bản Nhập kho'),
        ),
        migrations.AddField(
            model_name='importtbvt',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.TBVT', verbose_name='Vật tư'),
        ),
        migrations.AddField(
            model_name='exporttbvt',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='export_vt', to='summary.Document', verbose_name='Văn bản xuất kho'),
        ),
        migrations.AddField(
            model_name='exporttbvt',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.TBVT', verbose_name='Vật tư'),
        ),
        migrations.AddField(
            model_name='tbvt',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.TBVTBrand', verbose_name='Nhãn hiệu'),
        ),
        migrations.AddField(
            model_name='tbvt',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.TBVTType', verbose_name='Tên'),
        ),
        migrations.AddField(
            model_name='tbvt',
            name='unit_m',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.UnitMeasure', verbose_name='Đơn vị'),
        ),
    ]
