# Generated by Django 2.1 on 2018-08-31 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0010_auto_20180831_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitmeasure',
            name='short_text',
        ),
    ]
