# Generated by Django 2.1 on 2018-08-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0011_remove_unitmeasure_short_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbvt',
            name='MaTBVT',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Mã TBVT'),
        ),
        migrations.AlterField(
            model_name='tbvttype',
            name='short_text',
            field=models.CharField(help_text='Tối đa 5 ký tự', max_length=5, null=True, unique=True, verbose_name='Mã'),
        ),
    ]
