# Generated by Django 2.1 on 2018-08-31 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0013_document_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbtcmanage',
            name='sponsor',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('deparment__short_text', 'BT'), ('deparment__short_text', 'TT'), _connector='OR'), ('d_out__isnull', True), models.Q(_negated=True, position__short_text='CN')), null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Staff', verbose_name='Người quản lý'),
        ),
    ]
