# Generated by Django 2.1 on 2018-09-02 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0015_auto_20180831_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBVTManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('status', models.CharField(choices=[('im', 'Nhập kho'), ('ex', 'Xuất kho')], default='im', max_length=2, verbose_name='Nhập/Xuất')),
            ],
            options={
                'verbose_name': 'Nhập/Xuất Vật tư',
                'verbose_name_plural': 'Nhập/Xuất Vật tư',
                'ordering': ['document'],
            },
        ),
        migrations.RemoveField(
            model_name='exporttbvt',
            name='document',
        ),
        migrations.RemoveField(
            model_name='exporttbvt',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='importtbvt',
            name='document',
        ),
        migrations.RemoveField(
            model_name='importtbvt',
            name='unit',
        ),
        migrations.AlterModelOptions(
            name='tbvtbrand',
            options={'ordering': ['name'], 'verbose_name': 'Nhãn hiệu TBVT', 'verbose_name_plural': 'Nhãn hiệu TBVT'},
        ),
        migrations.AlterModelOptions(
            name='tbvttype',
            options={'ordering': ['name'], 'verbose_name': 'Loại TBVT', 'verbose_name_plural': 'Loại TBVT'},
        ),
        migrations.AlterField(
            model_name='document',
            name='date_crt',
            field=models.DateField(default='2018-09-02', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày lập'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='d_in',
            field=models.DateField(default='2018-09-02', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày vào làm'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.DateField(default='2018-09-02', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='tbtc',
            name='d_in',
            field=models.DateField(default='2018-09-02', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày mua'),
        ),
        migrations.AlterField(
            model_name='tbvtbrand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nhãn hiệu TBVT'),
        ),
        migrations.AlterField(
            model_name='tbvttype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên Vật tư'),
        ),
        migrations.DeleteModel(
            name='ExportTBVT',
        ),
        migrations.DeleteModel(
            name='ImportTBVT',
        ),
        migrations.AddField(
            model_name='tbvtmanage',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Document', verbose_name='Văn bản'),
        ),
        migrations.AddField(
            model_name='tbvtmanage',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.TBVT', verbose_name='Vật tư'),
        ),
    ]
