# Generated by Django 2.1 on 2018-09-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0016_auto_20180902_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbvtmanage',
            name='status',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('im', 'Nhập kho'), ('ex', 'Xuất kho')], default='im', max_length=2, verbose_name='Nhập/Xuất'),
        ),
        migrations.AlterField(
            model_name='document',
            name='sponsor',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('deparment__short_text', 'BT'), ('deparment__short_text', 'TT'), _connector='OR'), ('d_out__isnull', True), models.Q(_negated=True, position__short_text='CN')), null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Staff', verbose_name='Người quản lý'),
        ),
    ]
