# Generated by Django 2.1 on 2018-09-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0017_auto_20180902_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('im', 'Nhập'), ('ex', 'Xuất')], default='im', max_length=2, verbose_name='Nhập/Xuất'),
        ),
    ]
