# Generated by Django 2.1 on 2018-09-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0018_auto_20180902_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBVTDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaVB', models.CharField(max_length=100, null=True, unique=True, verbose_name='Mã VB')),
                ('name', models.CharField(max_length=200, verbose_name='Tên')),
                ('status', models.CharField(choices=[('im', 'Nhập'), ('ex', 'Xuất')], default='im', max_length=2, verbose_name='Nhập/Xuất')),
                ('date_crt', models.DateField(default='2018-09-03', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày lập')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Project', verbose_name='Công trình')),
            ],
            options={
                'verbose_name': 'Văn bản',
                'verbose_name_plural': 'Văn bản',
                'ordering': ['-date_crt'],
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='date_crt',
            field=models.DateField(default='2018-09-03', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày lập'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='d_in',
            field=models.DateField(default='2018-09-03', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày vào làm'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.DateField(default='2018-09-03', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='tbtc',
            name='d_in',
            field=models.DateField(default='2018-09-03', help_text='YYYY-MM-DD', null=True, verbose_name='Ngày mua'),
        ),
        migrations.AddField(
            model_name='tbvtdocument',
            name='sponsor',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('deparment__short_text', 'BT'), ('deparment__short_text', 'TT'), _connector='OR'), ('d_out__isnull', True), models.Q(_negated=True, position__short_text='CN')), null=True, on_delete=django.db.models.deletion.PROTECT, to='summary.Staff', verbose_name='Người quản lý'),
        ),
    ]
