# Generated by Django 2.1 on 2018-09-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0021_remove_tbtcdocument_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbtcdocument',
            options={'ordering': ['-date_crt'], 'verbose_name': 'Văn bản TBTC', 'verbose_name_plural': 'Văn bản TBTC'},
        ),
        migrations.AlterModelOptions(
            name='tbtcmanage',
            options={'ordering': ['-d_return', 'd_receive'], 'verbose_name': 'Phân bố TBTC', 'verbose_name_plural': 'Phân bố TBTC'},
        ),
        migrations.AlterModelOptions(
            name='tbvtdocument',
            options={'ordering': ['-date_crt'], 'verbose_name': 'Văn bản TBVT', 'verbose_name_plural': 'Văn bản TBVT'},
        ),
        migrations.RemoveField(
            model_name='tbtcmanage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='tbtcmanage',
            name='sponsor',
        ),
    ]
